// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: stream_service.proto

package vtplgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamService_WriteFrame_FullMethodName = "/data_models_stream.StreamService/WriteFrame"
	StreamService_ReadFrame_FullMethodName  = "/data_models_stream.StreamService/ReadFrame"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	WriteFrame(ctx context.Context, opts ...grpc.CallOption) (StreamService_WriteFrameClient, error)
	ReadFrame(ctx context.Context, in *ReadFrameRequest, opts ...grpc.CallOption) (StreamService_ReadFrameClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) WriteFrame(ctx context.Context, opts ...grpc.CallOption) (StreamService_WriteFrameClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_WriteFrame_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceWriteFrameClient{stream}
	return x, nil
}

type StreamService_WriteFrameClient interface {
	Send(*WriteFrameRequest) error
	CloseAndRecv() (*WriteFrameResponse, error)
	grpc.ClientStream
}

type streamServiceWriteFrameClient struct {
	grpc.ClientStream
}

func (x *streamServiceWriteFrameClient) Send(m *WriteFrameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceWriteFrameClient) CloseAndRecv() (*WriteFrameResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteFrameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamServiceClient) ReadFrame(ctx context.Context, in *ReadFrameRequest, opts ...grpc.CallOption) (StreamService_ReadFrameClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_ReadFrame_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceReadFrameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_ReadFrameClient interface {
	Recv() (*ReadFrameResponse, error)
	grpc.ClientStream
}

type streamServiceReadFrameClient struct {
	grpc.ClientStream
}

func (x *streamServiceReadFrameClient) Recv() (*ReadFrameResponse, error) {
	m := new(ReadFrameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	WriteFrame(StreamService_WriteFrameServer) error
	ReadFrame(*ReadFrameRequest, StreamService_ReadFrameServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) WriteFrame(StreamService_WriteFrameServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteFrame not implemented")
}
func (UnimplementedStreamServiceServer) ReadFrame(*ReadFrameRequest, StreamService_ReadFrameServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFrame not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_WriteFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).WriteFrame(&streamServiceWriteFrameServer{stream})
}

type StreamService_WriteFrameServer interface {
	SendAndClose(*WriteFrameResponse) error
	Recv() (*WriteFrameRequest, error)
	grpc.ServerStream
}

type streamServiceWriteFrameServer struct {
	grpc.ServerStream
}

func (x *streamServiceWriteFrameServer) SendAndClose(m *WriteFrameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceWriteFrameServer) Recv() (*WriteFrameRequest, error) {
	m := new(WriteFrameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamService_ReadFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFrameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).ReadFrame(m, &streamServiceReadFrameServer{stream})
}

type StreamService_ReadFrameServer interface {
	Send(*ReadFrameResponse) error
	grpc.ServerStream
}

type streamServiceReadFrameServer struct {
	grpc.ServerStream
}

func (x *streamServiceReadFrameServer) Send(m *ReadFrameResponse) error {
	return x.ServerStream.SendMsg(m)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_models_stream.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteFrame",
			Handler:       _StreamService_WriteFrame_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFrame",
			Handler:       _StreamService_ReadFrame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stream_service.proto",
}
